### ISSUE TITLE
seem to be haven some issues 

### ISSUE THREAD

**Issue by givemhell** [siku2/valuebot#2]
python -m valuebot results in 
https://pastebin.com/vdJhyXAR

**Comment by siku2** [comment]
The bot requires a [PostgreSQL](https://www.postgresql.org/) to store its data. If you're running the bot using Heroku the database is managed automatically for you, however if you run it manually, you need to take care of it yourself.

You can find the `postgres_dsn` setting in the [config.yml](https://github.com/siku2/valuebot/blob/master/config.yml) file and you can see that it defaults to "postgresql://postgres@localhost". In your case there doesn't seem to be a database running, so you get the `OSError: Multiple exceptions: [Errno 10061] Connect call failed ('::1', 5432), [
Errno 10061] Connect call failed ('127.0.0.1', 5432)` exception.
